apiVersion: apps/v1

kind: Deployment

metadata:

  name: todo-deployment

  labels:

    app: todo

spec:

  replicas: 5

  selector:

    matchLabels:

      app: todo

  template:

    metadata:

      labels:

        app: todo

    spec:

      containers:

      - name: todo

        image: akamanishh/todoapp:v1
        ports:

        - containerPort: 8000
